# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca03e90c377c52fffb76dfc8a44e9d61aeec94b294c958c482f6c20eb5df4b8978fb57f2f705efa706d6fe46b057ba8d408f095dafa33dda8aed0b320810e0cb

test:
  secret_key_base: 31ffe2e848e6b16acd7d10bab06e173827f6c0ff7b3e601a1922911747bf3b0c1e51ea66678be3dd8618158925e0e9a486762f6e034501f0c213185d36365edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
